* regfmt
~regfmt~ is a command line utility to generate SVG diagrams for control register-style data formats. It is inspired by the /dformat/ command from the /troff/ family of tools, however re-imagined using contemporary file formats.

Example output of ~regfmt~:

[[./tests/control/example0001.svg]]

* Features
- SVG output
- Modern configuration input file formats
  - YAML for register configuration
  - CSS for styling SVG output

* Examples

Generate the output file ~register.svg~ by invoking ~regfmt~ with the input file ~register.yaml~:

#+begin_src shell
  $ regfmt -o register.svg register.yaml
#+end_src

The file content of ~register.yaml~:

#+begin_src yaml :tangle tests/data/register.yaml
  ##
  # Example YAML file for regfmt

  width: 32
  endian: bigBit

  registers:
    - name: R1
      fields:
        - width: 8
          name: A4

        - width: 8
          name: A3

        - width: 8
          name: A2

        - width: 8
          name: A1
  layout:
    field-name-align: center
#+end_src

The corresponding output SVG file. 

# TODO: generate tests/control/register.svg

* Installation

*regfmt* uses a Python virtual environment to support its execution. From the top-level project directory, run the Makefile target ~install~ to create the virtual environment ~.venv~ and install the /pip/ modules required by *regfmt*. It will also create the symlink ~.venv/bin/regfmt~ to ~regfmt.py~.

#+begin_src sh
  $ make install
#+end_src

To initialize the environment invoke the following command:
#+begin_src sh
  $ source .venv/bin/activate 
#+end_src


* YAML Specification
TBD

* CSS Specification
TBD

* License
Copyright © 2022 Charles Y. Choi

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
